#!/usr/bin/env bash
# Build + run the NoC router waveform testbench, writing IP/NoC/wave/router.vcd.
#
#   ./IP/NoC/wave/run.sh                  # Verilator (fast; boundary signals)
#   ./IP/NoC/wave/run.sh --internals      # Icarus (slower; ALSO the router's
#                                         #   internal reservation state)
#   ./IP/NoC/wave/run.sh --view           # …and open the VCD in a viewer
#
# Both engines run the same testbench against the same netlist and both
# self-check the wormhole property, so agreement between them (and with
# `lake exe noc-test`, which drives a third simulator) is a real
# cross-check, not a formality.
#
# Which to use:
#   Verilator optimises the netlist's internal wires away — the `dut`
#   scope ends up holding only clk/rst/out, which is enough to SEE
#   wormhole switching (watch outV2/outF2 and the inR0/inR1 backpressure)
#   but not to EXPLAIN it.  Icarus does no such optimisation and dumps
#   every wire, including the per-input reservation state (_gen_a0 =
#   "input 0 is mid-packet", _gen_t0 = "the output it reserved") that is
#   the actual mechanism.  (The netlist used to carry ~20x duplicate
#   submodule instances and cloned wire families `_gen_a0_1`… — that
#   was Sparkle issue #107, fixed by the compiler commit this branch
#   sits on; see Router.lean's header.  Each internal name now appears
#   once.)
#
# router5.sv is regenerated by `lake build IP.NoC.Router` (the
# `#writeVerilogDesign` at the bottom of Router.lean), so the waveform
# always reflects the Lean source the proofs are about.
set -euo pipefail
cd "$(dirname "$0")/../../.."      # repo root — the tb's VCD path is repo-relative

WAVE=IP/NoC/wave
OBJ=$WAVE/obj_dir
MODE=${1:-}

lake build IP.NoC.Router           # refresh router5.sv from the Lean source

if [[ "$MODE" == "--internals" ]]; then
  iverilog -g2012 -o "$OBJ/router_tb_iv" "$WAVE/router5.sv" "$WAVE/router_tb.sv"
  vvp "$OBJ/router_tb_iv"
else
  # -Wno-fatal: the generated netlist trips Verilator style warnings
  # (e.g. UNOPTFLAT on the combinational arbiter→crossbar paths).
  verilator --binary --trace -j 0 \
    --top-module router_tb \
    -Wno-fatal \
    --Mdir "$OBJ" \
    -o router_tb \
    "$WAVE/router5.sv" "$WAVE/router_tb.sv"
  "$OBJ/router_tb"
fi

echo
echo "wrote $WAVE/router.vcd"

if [[ "$MODE" == "--view" || "${2:-}" == "--view" ]]; then
  # router.gtkw preselects the five signals that tell the story, with
  # sensible radices and group labels — see its header.
  if   command -v gtkwave >/dev/null; then (cd "$WAVE" && gtkwave router.vcd router.gtkw)
  elif command -v surfer  >/dev/null; then surfer "$WAVE/router.vcd"   # no .gtkw support
  else echo "no waveform viewer found (install gtkwave or surfer)"; fi
fi
